service: example-akka-http

provider:
  name: aws
  runtime: java8
  region: eu-west-1
  stage: dev

package:
  artifact: target/scala-2.12/hack9-lambda-1-assembly-1.0.jar

functions:
  api:
    handler: Route$EntryPoint::handle
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true
#      Uncomment below to keep the application warm
#      - schedule:
#          rate: rate(4 minutes)
#          input:
#            httpMethod: GET
#            path: /hello/keepWarm